import axios from "axios";
import Head from "next/head";
import Featured from "../components/Featured";
import Information from "../components/Information";
import People from "../components/People";
import ShopList from "../components/ShopList";
import styles from "../styles/Home.module.css";

export default function Home({ productList }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>7 Shop.com </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Featured />
      <Information />
      <ShopList productList={productList} />
      <People />
    </div>
  );
}
export const getServerSideProps = async () => {
  const res = await axios.get(
<<<<<<< HEAD
    "https://incredible-biscotti-8e24c5.netlify.app/api/product"
=======
    "http://localhost:3000/api/product"
>>>>>>> 8c5b0a82058842ab451a92a95dc2f07f8b9f5aa8

    // "https://incredible-biscotti-8e24c5.netlify.app/api/product"
  );
  return {
    props: {
      productList: res.data,
    },
  };
};
