import axios from "axios";
import Head from "next/head";
import Featured from "../components/Featured";
import Information from "../components/Information";
import People from "../components/People";
import ShopList from "../components/ShopList";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>7 Shop.com </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Featured />
      <Information />
      <ShopList />
      <People />
    </div>
  );
}
